# Generated by Django 3.2.4 on 2021-06-04 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('PJ', models.IntegerField(blank=True, null=True)),
                ('PG', models.IntegerField(blank=True, null=True)),
                ('PP', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=30)),
                ('nombre', models.CharField(blank=True, max_length=30)),
                ('apellido', models.CharField(blank=True, max_length=30)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('K', models.IntegerField(blank=True, null=True)),
                ('D', models.IntegerField(blank=True, null=True)),
                ('A', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.CharField(max_length=30)),
                ('imagen', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador_Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipos_jugadores.equipo')),
                ('jugador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipos_jugadores.jugador')),
            ],
        ),
        migrations.AddField(
            model_name='jugador',
            name='posicion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipos_jugadores.posicion'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='jugador1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jug1', to='equipos_jugadores.jugador'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='jugador2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jug2', to='equipos_jugadores.jugador'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='jugador3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jug3', to='equipos_jugadores.jugador'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='jugador4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jug4', to='equipos_jugadores.jugador'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='jugador5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jug5', to='equipos_jugadores.jugador'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='suplente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suplente', to='equipos_jugadores.jugador'),
        ),
    ]
